In [2]:
import numpy as np
vector=np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
v2=np.ones(10)
print(v2)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
v3=np.arange(0,20,1)
v3=v3[::-1]
v3

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [8]:
d = np.arange(10,25,5)
d


array([10, 15, 20])

In [21]:
a=np.array([1,4,6])
a

array([1, 4, 6])

In [8]:
#redimensionner
z=np.arange(9)
r=z.reshape(3,3)
r

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
t=np.eye(10)
t

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
array=np.random.random(5)
array

array([0.47830138, 0.08534403, 0.69286945, 0.14645507, 0.28703708])

In [32]:
matrix=np.random.random((5,5))
matrix

array([[0.09188714, 0.52539448, 0.31004115, 0.77783314, 0.31915867],
       [0.50089881, 0.06786901, 0.17801841, 0.76936205, 0.75506909],
       [0.94386436, 0.229175  , 0.96641308, 0.02071653, 0.11813247],
       [0.41396139, 0.16399825, 0.65148315, 0.38566843, 0.23697979],
       [0.23035282, 0.99631291, 0.29255337, 0.84457169, 0.15125577]])

In [39]:
min,max,mean =matrix.min(),matrix.max(),matrix.mean()
print(f"max({max}),min({min},mean({mean})")

max(0.996312908272172),min(0.02071652530473389,mean(0.4376388387508796)


In [42]:
array=np.array([[7,7,8],[4,6,7],[2,6,8]])
array.shape()

TypeError: 'tuple' object is not callable

In [44]:
#create matrix constant
array=np.full((2,8),2)
array

array([[2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2, 2]])

In [48]:
matrix=np.ones((4,4))
matrix[1:-1]=0
matrix

array([[1., 1., 1., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.]])

In [51]:
matrix=np.ones((4,4))
matrix[0:,1:-1]=0
matrix

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])

In [52]:
matrix=np.ones((4,4))
matrix[1:-1,1:-1]=0
matrix

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [11]:
matrix=np.random.random((5,5))
matrix.shape

(5, 5)

In [12]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a.shape)

(3, 3)


In [13]:
#Créez un tableau numérique 4x4 rempli de nombres aléatoires compris entre 0 et 1.
a = np.random.rand(4,4)
print(a)

[[0.93121799 0.06061338 0.5743174  0.4675509 ]
 [0.26895674 0.92936745 0.70946491 0.05764073]
 [0.10677408 0.33358314 0.30729568 0.59896269]
 [0.04271541 0.05649242 0.14389891 0.28703065]]


In [15]:
a = np.random.random(4)
print(a)

[0.75220767 0.19443694 0.90969523 0.16935966]


In [16]:
#Créez un tableau numpy 2x2 rempli d’entiers aléatoires compris entre 1 et 10 (inclus).
import numpy as np
a = np.random.randint(1, 11, (2,2))
print(a)


[[4 5]
 [9 9]]


In [23]:
#Créez un tableau numpy 2x3 et récupérez la deuxième ligne du tableau.
a = np.random.randint(1, 11, (2,3))
print(a)
print(a[1,:])

[[ 4  1  1]
 [ 9  5  9]
 [10  8  3]]
[9 5 9]


In [26]:
#Créez un tableau numpy 2x3 et récupérez la troisième colonne du tableau.
a = np.random.randint(1, 11, (2,3))
print(a[:,2])


[3 9]


In [27]:
#Créez un tableau numpy 3x3 et récupérez les éléments diagonaux du tableau.
a = np.random.randint(1, 11, (3,3))
print(np.diag(a))


[3 7 6]


In [28]:
#Créez un tableau numpy 2x2 et emportez le produit ponctuel du tableau avec lui-même.
a = np.random.randint(1, 11, (2,2))
b = np.dot(a,a)
print(b)


[[99 99]
 [77 88]]


In [29]:
#Créer un tableau numpy 2x3 et y ajouter un autre tableau 2x3 verticalement (c’est-à-dire le long des lignes)
a = np.random.randint(1, 11, (2,3))
b = np.random.randint(1, 11, (2,3))
c = np.vstack((a,b))
print(c)

[[ 3  2 10]
 [ 4  7  6]
 [10  2  6]
 [ 2  3  8]]


In [30]:
#Créer un tableau numpy 2x3 et y ajouter un autre tableau 2x3 horizontalement (c’est-à-dire le long des colonnes)
a = np.random.randint(1, 11, (2,3))
b = np.random.randint(1, 11, (2,3))
c = np.hstack((a,b))
print(c)

[[ 1  3  9 10  2  1]
 [ 7  1  8  7 10  5]]


In [ ]:
#Créer un tableau numpy 2x2 et calculer le déterminant du tableau
a = np.random.randint(1, 11, (2,2))
print(np.linalg.det(a))

In [31]:
#pour créer un tableau numpy 2x3 rempli de la valeur 7, vous pouvez utiliser le code suivant :
a = np.full((2, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]]


In [3]:
a = np.array([[1, 2, 3],[4, 5, 6]])

In [4]:
a[0,1]

2

In [5]:
a[:,1:3]

array([[2, 3],
       [5, 6]])

In [6]:
b = np.array([[2, 3],[5, 6]])

In [8]:
b[:,1]

array([3, 6])

In [10]:
b[:,0]

array([2, 5])

In [11]:
b[0,:]


array([2, 3])